routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

Route::get('/', 'HomeController@index')->name('home');

Route::resource('listing', 'ListingController')->middleware('auth');
Route::resource('user', 'UserController')->middleware('auth');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('type', 'u')->paginate(5);
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        ##VALIDATION PART##
        $rules = [
          'name'            => 'required',
          'email'           => 'required|email|unique:users,email',
        ];

        $message = [
            'name.required'       => "Name is required.",
            'email.email'         => "Email is required.",
        ];

        $this->validate($request, $rules, $message);
        ##VALIDATION PART##

        ##STORE IN DB
        User::create([
            'name'      => $request->input('name'),
            'email'     => $request->email,
            'type'      => 'u',
            'password'  => bcrypt('password'),
        ]);

        ###
        return redirect()->route('user.index')->with(['success-msg' => 'Record successfully created']);
        ###
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($user = User::find($id)) {

            return view('users.view', compact('user'));
        }

        return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($user = User::find($id)) {

            return view('users.edit', compact('user'));
        }

        return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)

    {
        ##VALIDATION PART##
        $rules = [
        'name'            => 'required',
      ];

      $message = [
          'name.required'       => "name is required",
      ];

      $this->validate($request, $rules, $message);
      ##VALIDATION PART##

      if (!$user = User::find($id)) {
          return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);
      }


      ###
      $user->name = $request->input('name');
      $user->save();
      ###
      // $user->update([
      //     'name'  => $request->input('name'),
      // ]);


      return redirect()->route('user.index')->with(['success-msg' => 'Record successfully updated.']);

  }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        if ($user = User::find($id)) {

            if($user->type == 'a'){
                return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);
            }

            $user->delete();

            return redirect()->route('user.index')->with(['success-msg' => 'Record successfully deleted.']);

        }

        return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);

    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Create New User
                        <a href="{{ route('user.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Return</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <form action="{{ route('user.store') }}" method="POST">
                        @csrf

                            @if(session('errors'))
                                <div class="alert alert-danger" role="alert">
                                    <p>Errors</p>
                                    @foreach($errors->all() as $error)
                                    &bull;{{ $error }}<br>
                                    @endforeach
                                </div>
                            @endif

                            @if(session('success-msg'))
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('success-msg') }}</p>
                                </div>
                            @endif


                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Email</label>
                            <input type="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="">
                        </div> 
                       

                        
                        <div class="form-group col-md-6">

                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Edit User
                        <a href="{{ route('user.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Return</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <form action="{{ route('user.update', $user->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                            @if(session('errors'))
                                <div class="alert alert-danger" role="alert">
                                    <p>Errors</p>
                                    @foreach($errors->all() as $error)
                                    &bull;{{ $error }}<br>
                                    @endforeach
                                </div>
                            @endif

                            @if(session('success-msg'))
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('success-msg') }}</p>
                                </div>
                            @endif


                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" name="name" value="{{ $user->name }}" class="form-control" >
                        </div>

                        <div class="form-group col-md-6">
                            <label>Email</label>
                            <input type="text" name="email" value="{{ $user->email }}" class="form-control" >
                        </div>

                        

                        <div class="form-group col-md-6">

                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h2>List of User</h2>
  <p>

  <a href="{{ route('user.create') }}">
    <button type="button" class="btn btn-outline-primary">Add New User</button>  
    </a> 
    </p>      
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Created At</th>
        <th>Action</th>
        

</div>
      </tr>
    </thead>
    <tbody>
    
    @forelse($users as $user)

      <tr>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td>{{ $user->created_at }}</td>

        
        <td> 
        <div class="btn-group" role="group" aria-label="Basic example">
        
                <a href="{{ route('user.show', [$user->id]) }}">
                    <button type="button" class="btn btn-success btn-sm">View</button>
               </a>

               <a href="{{ route('user.edit', [$user->id]) }}">
                    <button type="button" class="btn btn-warning btn-sm">Edit</button>
              </a>

              

            @if($user->type != 'a')
            <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                @method('DELETE')
                @csrf
                <button class="btn btn-danger btn-sm" type="submit" onclick="confirm('Are you sure to delete this data ?')">Delete</button>
            </form>
            @endif
                                 
      </div>
              

              </td>
        

          </tr>
                             @empty
                            <tr>
                                <td colspan="5">No Record Found</td>
                            </tr>
                            @endforelse

    </tbody>
  </table>

  <div style="float:left; margin-right: 5px;">
                        <div class="pagination">
                            <h5 class="page-item"> Showing {{$users->total()}} - {{$users->total()}} of {{$users->total()}}</h5>
                        </div>
                    </div>
                    <div style="float:right; margin-right: 5px;">
                        {!! $users->appends(\Request::except('page'))->render("pagination::bootstrap-4") !!} 
                    </div>
                    
</div>
@endsection

resources/views/users/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>View User
                        <a href="{{ route('user.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Return</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
               
                     <div class="form-group col-md-6">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ $user->name }}" class="form-control" >
                    </div>

                    <div class="form-group col-md-6">
                        <label>Email</label>
                        <input type="text" name="email" value="{{ $user->email }}" class="form-control" >
                    </div>

                    <div class="form-group col-md-6">
                        <label>Created At</label>
                        <input type="text" name="created_at" value="{{ $user->created_at }}" class="form-control">
                    </div>
                   

                </div>
            </div>
        </div>
    </div>
</div>
@endsection